### ISSUE TITLE
Question on token max limit (8,192 vs. 4,096)

### ISSUE THREAD

**Issue by mgh1** [whaleloops/KEPT#2]
Dear @whaleloops ,

In your excellent [paper](https://arxiv.org/pdf/2210.03304.pdf), you mentioned you use the [Clinical Longformer from Li et al., 2022](https://huggingface.co/yikuan8/Clinical-Longformer). In several places in the paper you mentioned the max token limit is 8,192 tokens, however the Clinical Longformer from Li says the max limit is 4,096 tokens. 

Please explain this gap (8,192 vs. 4,096). Thank you.

**Comment by whaleloops** [comment]
Good question! You could use the allenai [original](https://github.com/allenai/longformer/blob/master/scripts/convert_model_to_long.ipynb) or [our script](https://github.com/whaleloops/KEPT/blob/main/convert_model_to_long.ipynb) to change the max token limit, by changing max_pos=4096 to max_pos=16384 (or even more).
